### ISSUE TITLE
[Bug]: ManagedPeripheral, on iOS, notifications fails to automatically re-subscribe after the device disconnected and connected again.

### ISSUE THREAD

**Issue by wagenheimer** [shinyorg/shiny#1096] opened 2022-09-13 16:35 UTC
### Component/Nuget

BluetoothLE Client (Shiny.BluetoothLE)

### What operating system(s) are effected?

- [ ] iOS 12
- [ ] iOS 13
- [ ] iOS 14
- [X] iOS 15
- [ ] Mac Catalyst
- [ ] Android 8
- [ ] Android 9
- [ ] Android 10
- [ ] Android 11
- [ ] Android 12

### What platform(s) are effected?

- [ ] MAUI
- [ ] Xamarin Native
- [X] Xamarin Forms

### Steps To Reproduce

1 - Create a ManagedPeripheral from a Device and Connect to it
2 - Subscribe to a notification of this device:
`ManagedPeripheral.WhenNotificationReceived("97d8ccb6-b6b6-4bc8-a7ba-5b4ecb9e4f62","875607c1-1f96-449c-b4d5-14dab172d5e6").Subscribe(result => Process(result));`
4 - Test it, and see the notifications being received as expected. 
5 - Turn off the Device
6 - Turn on the Device again
7 - The device will automatically reconnect but will show an error, and the Notification will no longer be received.

```
System.ArgumentException: No characteristic found - 97d8ccb6-b6b6-4bc8-a7ba-5b4ecb9e4f62/875607c1-1f96-449c-b4d5-14dab172d5e6
  at Shiny.BluetoothLE.Extensions+<>c__DisplayClass15_0.<Assert>b__0 (Shiny.BluetoothLE.IGattCharacteristic ch) [0x00028] in <1c688311e7f04d34b71919a7f9529315>:0 
  at System.Reactive.Linq.ObservableImpl.Do`1+OnNext+_[TSource].OnNext (TSource value) [0x00000] in <3ad0cc868be642ac8d0c22906bb12ddb>:0
```

Everything works as expected on Android. The problem only happens on iOS.

### Expected Behavior

The device should automatically re-subscribe to the notification.

### Actual Behavior

An error occurs and the notification is not re-subscribed.

### Code of Conduct

- [X] My reproducible sample is NOT FROM THE SHINY SAMPLES REPOSITORY!  If you file an issue that says 'use shiny sample', YOU WILL BE BANNED FROM THE SHINY REPOS.  Read the code of conduct for why we care about this!
- [X] I am using the latest stable version from nuget (sponsors can discuss previews in discord)
- [X] I agree to follow this project's Code of Conduct

**Comment by wagenheimer** [comment] 2022-09-13 17:28
I'm testing with another device.  It seems to be some problem with Discover Services and Characteristics on iOS. On these another device, I cannot event read manually values from some Characteristics that I know it exists.

`var rawValue = await ManagedPeripheral.Read("000030ff-0000-1000-8000-00805f9b34fb", "0003000-0000-1000-8000-00805f9b34fb").ToTask(); ;`

It shows me the error :

`No characteristic found - 30ff/00003000-0000-1000-8000-00805f9b34fb`

**Comment by aritchie** [comment] 2022-09-14 14:36
Works fine for me.  I just tried it with my code without issue.  Since no reproducible sample has been added, I'm closing this since it does not meet the terms of filing an issue

**Closed by aritchie** 2022-09-14 14:36 UTC
Labels: bug, unverified
