### ISSUE TITLE
Android 10 RequestAccess with "Allow only when the app is in use" will return AccessState.Denied

### ISSUE THREAD

**Issue by ricardomomm** [shinyorg/shiny#487] opened 2020-12-22 18:17 UTC
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [X] Android
 - [ ] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [ ] Core
 - [X] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [ ] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library

- 1.2.0.1755

## Version of OS(s) listed above with issue

- Android Q (api 29)

## Steps to Reproduce
1. Create code to Request for Location Access Permission with BackgroundMode = true
2. Deploy and run it in an Android Q device
3. Select "Allow only when the app is in use"

## Expected Behavior
GpsManagerImpl.RequestAccess method should return AccessState.Available or AccessState.Restricted if background mode is requested

## Actual Behavior
GpsManagerImpl.RequestAccess method is returning AccessState.Denied

**Comment by ricardomomm** [comment] 2020-12-22 18:23
Trying the latest preview version will actually enter in an infinite loop and crash

2.0.0.2394-preview

[stacktrace.txt](https://github.com/shinyorg/shiny/files/5731428/stacktrace.txt)

**Comment by aritchie** [comment] 2020-12-22 18:45
Please include a reproducible sample.  

As for the previews, they are intended for internal use only right now

**Comment by ricardomomm** [comment] 2020-12-23 13:37
Reproducible sample attached

[ShinyExample.zip](https://github.com/shinyorg/shiny/files/5735463/ShinyExample.zip)

**Comment by bPoller2810** [comment] 2020-12-28 19:35
How is the progress on this at the moment? This breaks existing production apps at the moment.

**Comment by aritchie** [comment] 2020-12-29 01:22
@bPoller2810 you tell me.  You got a PR since this is breaking your app?

**Comment by bPoller2810** [comment] 2020-12-29 05:06
oh wow. i am sorry for asking. i will see if i get a meeting with my boss today if i am allowed to shedule time to fix your project. 

are you kind of mad just because i asked? cmon whats wrong?

**Comment by aritchie** [comment] 2020-12-29 05:24
@bPoller2810 You seem to think I'm here to make fixes for you and report a timeframe to you for something I do for free.  You aren't offering to fix it, you don't support the project, and yet you are using it for money making purposes.  It's attitudes like that which ruin OSS, so yes - you should be sorry for asking. 

And since I can already sense entitlement in your reply as well as the thumbs down on my reply - I'm just going to do us both a favor and ban you from the project.

**Comment by aritchie** [comment] 2021-01-07 16:46
This has been fixed in the latest 2.0 preview

**Closed by aritchie** 2021-01-07 16:46 UTC
Labels: more-info-needed, s/unverified, t/bug 👾
