### ISSUE TITLE
VTable Exception after updating to 2.2.0.2814-preview

### ISSUE THREAD

**Issue by jmichas** [shinyorg/shiny#658] opened 2021-07-23 02:14 UTC
ONLY active OSS maintainers of other projects OR ACTIVE project sponsors can ask questions here.  If you don't do either of these things - DO NOT FILE HERE OR THIS WILL BE CLOSED!
THERE IS NO SUPPORT ON PREVIEW/BETA VERSIONS!  

Give as much details as humanly possible if you want any sort of answer!

Enter Question Below (don't delete this line)
After updating to the latest preview I get the following exception when running on simulator or device. If I remove the `ShinyFinishedLaunching` from my `FinishedLaunching` method I will get past but fail on first dependency (obviously).
Not sure if this is a me problem or a shiny problem. I was hoping to use the fixed Jobs stuff in 2.2. I posted this as a question because I thought maybe it could be simply answered.
Also, I have of course completely cleaned and rebuilt and still get the error.

````
2021-07-22 21:16:14.735061-0400 MyApp.Mobile.iOS[69111:14781633] VTable setup of type MyApp.Mobile.Startup failed
2021-07-22 21:16:14.739046-0400 MyApp.Mobile.iOS[69111:14781633]   at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:86 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:65 
  at UIKit.UIApplication.Main (System.String[] args, System.Type principalClass, System.Type delegateClass) [0x00000] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:75 
  at MyApp.Mobile.iOS.Application.Main (System.String[] args) [0x00002] in /Data/Projects/MyApp/Mac Repo/MyApp App/MyApp.Mobile/MyApp.Mobile.iOS/Main.cs:20
````

**Comment by jmichas** [comment] 2021-07-23 03:22
Just to follow up, I don't get the exception after downgrading to the 2.1 release.

**Comment by aritchie** [comment] 2021-07-23 03:48
VTable issues are usually binary incompatibilities due to something not fully updating or an external library that is matching against a different version.  I need a full reproducible sample in order to figure these out. 

I am using the preview in 2 other projects without issue

**Comment by aritchie** [comment] 2021-07-26 15:24
Closing as no reply or reproducible sample supplied

**Closed by aritchie** 2021-07-26 15:24 UTC
Labels: sponsor 💖

**Comment by herrquark** [comment] 2021-08-18 19:36
Same problem (`VTable setup of type MobileApp.Startup failed`) here on Android, didn't test on iOS. "Fixed" it by reverting to 2.1

**Comment by aritchie** [comment] 2021-08-18 20:09
@herrquark Add some sort of additional info.  I'm not going to guess at the issue.

**Comment by jmichas** [comment] 2021-08-28 20:20
Ok, I finally was able to find time to make a repro of this.
As far as I can tell this is caused by Shiny.Prism. When I change my startup to inherit from ShinyStartup it gets past the VTable error and dies on some service not resolving.

Let me know if you csn take a look at this and see what the problem is, I really need to get my shiny nugets updated to the latest because I'm sure there are bug fixes in them I need to get my app out the door.

Thanks a lot.
(oh and don't mind the project name, I started it for Dan a while back for an issue with Regions and then kept messing around with it for test ideas)
[PrismBugsRUs.zip](https://github.com/shinyorg/shiny/files/7071433/PrismBugsRUs.zip)

**Comment by aritchie** [comment] 2021-08-29 14:21
@jmichas Shiny.Prism isn't part of the Shiny project.  If you've already determined things work without it, I'd suggest sending a patch to Shiny.Prism or moving on without it.

**Comment by jmichas** [comment] 2021-08-29 14:29
@aritchie Yeah, I realized that after I posted and was doing some more work last night trying to get to the root cause. 

Is there an example of how I would do this without Shiny.Prism? 

I have looked at so many of your and Dan's blogs, videos, code samples, etc. but not much if any is up to date. I still have yet to find an example of the proper way to register platform services in Shiny. That is what is breaking Shiny.Prism anyway, PrismStartup does not implement `RegisterPlatformServices` because it is built against an old version of Shiny (2.0.0).

**Comment by aritchie** [comment] 2021-08-29 14:47
You can find an example of registering platform specific services here: https://shinylib.net/setup/startup

**Comment by jmichas** [comment] 2021-08-29 17:08
@aritchie Thanks. One last question, can Shiny.Framework be used with Unity container and would it be a replacement for Shiny.Prism? 
I am Prism+Unity+Shiny.

**Comment by aritchie** [comment] 2021-08-30 01:51
@jmichas No.  It only supports DryIoc to cutdown on the support.  It's meant as a one stop shop to get rolling with Shiny, Prism, & RXUI.  DryIoc (and Unity) is really only required for Prism, otherwise Shiny would just run on the standard Msft DI.  

The other reason I won't offer Unity is because it is a damn slow container, old, and I don't believe it is under active dev any longer.  The startup time of the containers need to be lightning or the background services won't run.

**Comment by jmichas** [comment] 2021-08-30 02:44
Ok, thanks for the info. Looks like I'll swap out Unity for DryIoc and try and use Shiny.Framework. Seems like there is no reason to use Shiny.Prism if framework is the future of Prism+Shiny integration. I've been swimming up stream too long I feel.

**Comment by jmichas** [comment] 2021-08-30 18:57
I am adding this last comment to help anyone else who may have run into the issues I did trying to shoehorn Shiny into an existing Prism + Unity project. I had a number of problems trying to make Shiny.Prism work with the later versions of Shiny and I am sure it had some knock on effects with issues I wasn't aware of. 

What worked for me in the end was ditching Shiny.Prism and swapping out Unity for DryIoc. This allowed me to migrate to Shiny.Framework. And everything has started to run as expected now.

Some issues you may have switching to DryIoc is if you have any named instances of registrations.
For example:
If you had `IStep` and maybe registered a bunch of implementations of it like:
````
containerRegistry.Register<IStep,IsUserLoggedIn>(nameof(IsUserLoggedIn));
containerRegistry.Register<IStep,IsPhoneNumberVerified>(nameof(IsPhoneNumberVerified));
...
````
And you used these for property injection using Unity's `[Dependency(nameof(IsUserLoggedIn))]` attribute, you will need to do something different for DryIoc.

I simply made vanity interfaces for each class, such as:
````
public interface IIsUserLoggedIn : IStep{}
public class IsUserLoggedIn : IIsUserLoggedIn 
{
    ...
}
````
This way you can register each step and use them all as an `IStep` without needing to refer to the registration by name.

Probably overall a better approach but being a long time Unity user I just used the named style when needed.

Other than that the switch is painless and I am seeing much better performance from DryIoc as noted by Allan.

Migrating to Shiny.Framework should be straightforward using the sample project in the repo.
