### ISSUE TITLE
[Android] BLE Synchronization

### ISSUE THREAD

**Issue by mongomeryplanet670** [shinyorg/shiny#577] opened 2021-05-05 20:27 UTC
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [X] Android
 - [ ] UWP

## Feature Library
 - [ ] Core (Jobs, Settings, Initialization)
 - [ ] Locations (GPS, Geofencing, Motion Activity)
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] NFC
 - [ ] Push - Native
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase
 - [ ] Sensors
 - [X] BluetoothLE Client
 - [ ] BluetoothLE Hosting
 - [ ] Beacons
 - [ ] SQLite Integration

## Version of Library
Shiny.BluetoothLE 2.0.0.2639

## Version of OS(s) listed above with issue
All

## Steps to Reproduce
1. It is very easy to make a "mistake" which triggers a call to a native Android Ble method on a thread which is not the main thread. This leads to Gatt error 133 and disconnection of the ble device which is hard to uncover and fix.

2. It is very easy to make a "mistake", especially when using reactivex, which triggers a call to a native Android Ble method from "inside" a native Ble callback. By "inside" i mean the code will not let the callback return, before calling a Ble method again. This is prohibited by Android and also triggers Gatt error 133 and disconnection. And of course it's very very hard to uncover.

3. The locking mechanism used by the `Invoke`  method (ie: `Synchronize(syncLock)`) is a clever idea to serialize calls to native android Ble methods. Unfortunately it does not work as expected. Because of Tasks. Tasks are not threads, they are scheduled to threads from inside a thread pool by a task scheduler. And this scheduler can schedule 2 tasks to the same thread if one of them is waiting.

Here it should be quite simple as all calls should be on the main thread, so they should lock correctly. Unfortunately nothing prevents a developer to initiate a call on a worker thread. Even maybe without knowing it.

A second point against this lock, is the main thread is also used to call Android Ble, and most UI things, so locking it may leads to deadlock, timeouts, or slowness.

I agree this 3rd point may be litigious, but in my case it makes the app much more reliable.

## Expected Behavior
Make the life of developers easier.

## Actual Behavior
For 1) insights:  
Currently, there is not enough insights in the ble lib to diagnose any of these 3 issues. Leading to suicides among developers. 

For 2) callbacks:  
There is no mechanism to prevent what is described.

For 3) sync:  
Already described above. I will be happy to provide more explanations.

## Proposals
For 1) insights:  
- Add more logs, using a log service. For example detect if a call is not on the main thread (if the flag is set) and log it. Throwing exceptions may not be enough for most devs, as it's quite difficult to setup a logger in an application correctly.

For 2) callbacks:  
- An easy 'fix' (if that can be called a fix) would be to trigger the callback events outside the callback itself. The following code is a way of doing that:

```csharp
public class GattCallbacks : BluetoothGattCallback
    {
        //public override void OnPhyRead(BluetoothGatt? gatt, [GeneratedEnum] ScanSettingsPhy txPhy, [GeneratedEnum] ScanSettingsPhy rxPhy, [GeneratedEnum] GattStatus status) => base.OnPhyRead(gatt, txPhy, rxPhy, status);
        //public override void OnPhyUpdate(BluetoothGatt? gatt, [GeneratedEnum] ScanSettingsPhy txPhy, [GeneratedEnum] ScanSettingsPhy rxPhy, [GeneratedEnum] GattStatus status) => base.OnPhyUpdate(gatt, txPhy, rxPhy, status);

        public Subject<GattCharacteristicEventArgs> CharacteristicRead { get; } = new Subject<GattCharacteristicEventArgs>();
        public override void OnCharacteristicRead(BluetoothGatt gatt, BluetoothGattCharacteristic characteristic, GattStatus status)
            => Task.Run(() => Xamarin.Essentials.MainThread.BeginInvokeOnMainThread(() => this.CharacteristicRead.OnNext(new GattCharacteristicEventArgs(gatt, characteristic, status))));


        public Subject<GattCharacteristicEventArgs> CharacteristicWrite { get; } = new Subject<GattCharacteristicEventArgs>();
        public override void OnCharacteristicWrite(BluetoothGatt gatt, BluetoothGattCharacteristic characteristic, GattStatus status)
            => Task.Run(() => Xamarin.Essentials.MainThread.BeginInvokeOnMainThread(() => this.CharacteristicWrite.OnNext(new GattCharacteristicEventArgs(gatt, characteristic, status))));


        public Subject<GattCharacteristicEventArgs> CharacteristicChanged { get; } = new Subject<GattCharacteristicEventArgs>();
        public override void OnCharacteristicChanged(BluetoothGatt gatt, BluetoothGattCharacteristic characteristic)
            => Task.Run(() => Xamarin.Essentials.MainThread.BeginInvokeOnMainThread(() => this.CharacteristicChanged.OnNext(new GattCharacteristicEventArgs(gatt, characteristic))));


        public Subject<GattDescriptorEventArgs> DescriptorRead { get; } = new Subject<GattDescriptorEventArgs>();
        public override void OnDescriptorRead(BluetoothGatt gatt, BluetoothGattDescriptor descriptor, GattStatus status)
            => Task.Run(() => Xamarin.Essentials.MainThread.BeginInvokeOnMainThread(() => this.DescriptorRead.OnNext(new GattDescriptorEventArgs(gatt, descriptor, status))));


        public Subject<GattDescriptorEventArgs> DescriptorWrite { get; } = new Subject<GattDescriptorEventArgs>();
        public override void OnDescriptorWrite(BluetoothGatt gatt, BluetoothGattDescriptor descriptor, GattStatus status)
            => Task.Run(() => Xamarin.Essentials.MainThread.BeginInvokeOnMainThread(() => this.DescriptorWrite.OnNext(new GattDescriptorEventArgs(gatt, descriptor, status))));


        public Subject<MtuChangedEventArgs> MtuChanged { get; } = new Subject<MtuChangedEventArgs>();
        public override void OnMtuChanged(BluetoothGatt gatt, int mtu, GattStatus status)
            => Task.Run(() => Xamarin.Essentials.MainThread.BeginInvokeOnMainThread(() => this.MtuChanged.OnNext(new MtuChangedEventArgs(mtu, gatt, status))));


        public Subject<GattRssiEventArgs> ReadRemoteRssi  { get; } = new Subject<GattRssiEventArgs>();
        public override void OnReadRemoteRssi(BluetoothGatt gatt, int rssi, GattStatus status)
            => Task.Run(() => Xamarin.Essentials.MainThread.BeginInvokeOnMainThread(() => this.ReadRemoteRssi.OnNext(new GattRssiEventArgs(rssi, gatt, status))));


        public Subject<GattEventArgs> ReliableWriteCompleted { get; } = new Subject<GattEventArgs>();
        public override void OnReliableWriteCompleted(BluetoothGatt gatt, GattStatus status)
            => Task.Run(() => Xamarin.Essentials.MainThread.BeginInvokeOnMainThread(() => this.ReliableWriteCompleted.OnNext(new GattEventArgs(gatt, status))));


        public Subject<GattEventArgs> ServicesDiscovered { get; } = new Subject<GattEventArgs>();
        public override void OnServicesDiscovered(BluetoothGatt gatt, GattStatus status)
            => Task.Run(() => Xamarin.Essentials.MainThread.BeginInvokeOnMainThread(() => this.ServicesDiscovered.OnNext(new GattEventArgs(gatt, status))));


        public Subject<ConnectionStateEventArgs> ConnectionStateChanged { get; } = new Subject<ConnectionStateEventArgs>();
        public override void OnConnectionStateChange(BluetoothGatt gatt, GattStatus status, ProfileState newState)
        {
            //Never call another android ble method while in a callback
            Task.Run(() => Xamarin.Essentials.MainThread.BeginInvokeOnMainThread(() => ConnectionStateChanged.OnNext(new ConnectionStateEventArgs(gatt, status, newState))));
        }
    }
```

For 3) sync:  
- ReactiveX is extensible enough to be able to use an async Semaphore instead of a lock, thus not locking the thread but effectively preventing multiple simultaneous calls of Android Ble methods. The followind code is a re-implementation of the Invoke method doing that:

```csharp
        private readonly SemaphoreSlim sync = new SemaphoreSlim(1,1);

        public IObservable<T> Invoke<T>(IObservable<T> observable)
        {
            if (!this.ManagerContext.Configuration.AndroidUseInternalSyncQueue)
                return observable;

            return Observable.Create<T>(async ob =>
            {
                await sync.WaitAsync();
                try
                {
                    var result = await observable.Synchronize();
                    ob.OnNext(result);
                }
                catch (Exception e)
                {
                    ob.OnError(e);
                }
                finally
                {
                    sync.Release();
                }
            });
        }
```

**Comment by aritchie** [comment] 2021-05-05 22:37
Please stick to filing actual issues as something that is broken with an exception.  There isn't an actual problem here and the underlying commands are synchronized to prevent GATT133 unless the user disables it.  I also don't want to bumping on the main thread until right before the call is neecded.

**Comment by aritchie** [comment] 2021-05-05 23:00
I don't want to close this, but I need something more than a laundry list of issues.  They aren't issues until there is something I can work with.

**Comment by aritchie** [comment] 2021-05-06 01:21
ok, so after further review - I agree with most points.  The lock does work and blocks multiple tasks, but hence - it is a full lock.  I like the semaphore approach even better than the original queue I had before this.   

Logging is a slippery slope and most people won't be digging.  It is usually enough to use the OS and errors should be bubbling through appropriately, but I'm open to more specific suggestions.  

As far as async on the android callbacks, this is something I definitely don't want to do.  At least, not in the way it is done.  This one needs to be thought out a bit and in some cases, the user code does have to be responsible for things.  

All for 1 and 3... 2 just needs some additional thinking.  Thanks for the detailed post.  Definitely still would like repros though as the issues need to be mostly proven.

**Comment by MKGNZ** [comment] 2021-05-06 13:35
To help with the further review and that it **might** not really need to be in the UI Thread please take a look at these 2 links whenever and if you have time:

[https://medium.com/@martijn.van.welie/making-android-ble-work-part-3-117d3a8aee23](url)
[https://punchthrough.com/android-ble-guide/](url)

for solution 2 scheduling on the main thread actually is not safe because Android is reusing the GattCharacteristic and you can lose the value between the scheduling of the thread and a new incoming data that will override the value. (this info is close to the end of the first link)

PS: (I'm not sure about this. If anyone has a documentation that says otherwise please send me the link)
All articles and android docs that I have read they don't mention that it requires the UI thread. Actually they say don't use the UI thread. Again I heard and saw a lot of requests done in the UI thread but no doc says that must. (I guess I'll have to create a native Android app to test myself)

**Comment by aritchie** [comment] 2021-05-06 13:44
@MKGNZ Thanks for the articles.  I'll take a look.  Not all of the Android BLE mechanisms are created equal.  Samsung's version used to crap right out if it was on the main thread.  Perhaps things have improved.  I can/should make this configurable just in case.

**Comment by aritchie** [comment] 2021-05-16 02:28
Since I still have nothing but quotes on "mistakes" and nothing actually reproducible, I am closing this.  I do agree that the locking mechanism had to change and it has.   There has always been a way to disable operations from running on the main thread via BleConfiguration.AndroidShouldInvokeOnMainThread and the default on it is now false.  

All errors are bubbled up to the caller, so adding a ton of logging in the internals is also not worthwhile as 99.9% of users aren't going to do that level of effort.

**Closed by aritchie** 2021-05-16 02:28 UTC
Labels: more-info-needed, s/unverified, t/bug 👾
