### ISSUE TITLE
Issue with permissions for use-in-app only

### ISSUE THREAD

**Issue by lborges12** [shinyorg/shiny#451] opened 2020-11-12 11:31 UTC
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!  PLEASE DON'T ASK FOR WORKAROUNDS OR TIMELINES - THIS IS FREE SOURCE CODE

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [x] Core
 - [x] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [ ] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library
2.0.0.2356-preview

## Version of OS(s) listed above with issue
Android 10

## Steps to Reproduce
1. Permit the shiny locations to use them on application only.
2. Start the listener.
3. As soon as the listener starts it asks me for permissions including "LocationAlways" which is the background one which I don't want to show.
4. Select "Keep while-in-use access".
5. Crash

## Expected Behavior
The app would continue working while on foreground locations only.

## Actual Behavior
It crashes to this exception:

`{System.ArgumentException: Invalid State Denied
  at Shiny.GeneralExtensions.Assert (Shiny.AccessState state, System.String message, System.Boolean allowRestricted) [0x00029] in <19f09e8d8f464b7fa4b8360dcabcc7c3>:0 
  at Shiny.Locations.GpsManagerImpl.StartListenerInternal (Shiny.Locations.GpsRequest request) [0x0007c] in <aee0c0bad98f46d1a8568c8a891695c8>:0 
  at Shiny.Locations.GpsManagerImpl.StartListener (Shiny.Locations.GpsRequest request) [0x00072] in <aee0c0bad98f46d1a8568c8a891695c8>:0 
  at App.ViewModels.Shared.HomeViewModel._StartShinyLocationAsync (System.Boolean _useBackground) [0x002c3] in C:\Projects\App\App\ViewModels\Shared\HomeViewModel.cs:1946 }`

The line 1946 where the error occurs is the startlistener that will follow:

`if (gpsRequest == null)
                    gpsRequest = new GpsRequest();

                realTime = GpsRequest.Realtime(true);
                
                gpsRequest.UseBackground = _useBackground;
                gpsRequest.Priority = realTime.Priority;
                gpsRequest.Interval = realTime.Interval;
                gpsRequest.ThrottledInterval = realTime.ThrottledInterval;
                

                await _gpsManager.StartListener(gpsRequest);`

**Comment by aritchie** [comment] 2020-11-12 13:19
That's not a crash - that's a controlled exception because the listener believes it cannot offer the appropriate functionality.  The issue is that it isn't asserting on the proper permission requests.  This will be fixed for a later preview

**Comment by lborges12** [comment] 2020-11-17 16:42
Hi @aritchie ! Thanks alot for the fast commit. I was trying out the fix that you issued but in android 10, in the popup that asks for permissions if I click on the "Use in-app only location" your function Assert() in the Extensions_General.cs is returning AccessState.Denied

**Comment by aritchie** [comment] 2020-11-17 16:44
@lborges12 submit a PR if you know the issue you need solved please

**Comment by aritchie** [comment] 2020-11-17 16:51
@lborges12 This looks fine to me now.  You'll need to submit a FULL reproducible sample OR better yet, if you find what it is that isn't working - submit a PR.

**Closed by aritchie** 2020-11-17 16:51 UTC
Labels: s/unverified, t/bug 👾
