### ISSUE TITLE
Cannot initialize shiny on android using the androidhooks class. 

### ISSUE THREAD

**Issue by arivera12** [shinyorg/shiny#495] opened 2021-01-25 04:34 UTC
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [X] Android
 - [ ] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [X] Core
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [ ] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library
Install-Package Shiny.Core -Version 2.0.0.2448-preview

## Version of OS(s) listed above with issue

LATEST

## Steps to Reproduce
Install the package
Try look the androidhooks class

## Expected Behavior

See the androidhooks.cs class to initialize android

https://github.com/shinyorg/shiny/blob/dev/src/Shiny.Core/Platforms/Android/AndroidHooks.cs

## Actual Behavior

Seems no to exists in the nuget package

![image](https://user-images.githubusercontent.com/5600102/105661910-f4d24300-5ea4-11eb-8979-91e0b3c3edf8.png)

**Comment by aritchie** [comment] 2021-01-25 14:06
Is your major target android 10?  

Please include more details like a reproducible sample ESPECIALLY for the preview since it is still in active development and isn't meant for general issues like this right now.

**Comment by arivera12** [comment] 2021-01-25 16:14
> Is your major target android 10?

No, I just change it to 10 but I still don't get any reference from androidhooks class

> 
> Please include more details like a reproducible sample ESPECIALLY for the preview since it is still in active development and isn't meant for general issues like this right now.

I would like to include a reproducible sample but it will not do anything because I just don't get a reference of shiny to initialize it on android.

I have surfed the repository entirely I notice that master branch is out updated and the branches of dev and preview are the one that are being currently maintained.

I dig into the source code since the sample to initialize shiny are using the old version style 1.2.0.1755 but I am using 2.0.0.2279 which should be the dev branch.

As I discovered this should be the new way to initialize on android but I dont get any reference from it from visual studio intellisense is like it doesn't exists at all.

https://github.com/shinyorg/shiny/blob/preview/src/Shiny.Core/Platforms/Android/AndroidHooks.cs

Shiny works excellent on ios and I was able to initialize it like this
![image](https://user-images.githubusercontent.com/5600102/105731036-5a561c00-5f05-11eb-842c-70e44347bd12.png)

**Comment by aritchie** [comment] 2021-01-25 17:02
* You often need to restart visual studio for it to pick up the new version references.  

* I need a reproducible sample if you want help with this as this works fine for me.  If you can't provide one than I'll have to close this issue as I'm not going to guess at the problem.

* 1.2 is stable.  Use it if you want to file bugs in the future.  2.0 is still being worked on and is open for PR's, not general usage.

**Comment by arivera12** [comment] 2021-01-25 17:32
> * You often need to restart visual studio for it to pick up the new version references.

I did few times.

> * I need a reproducible sample if you want help with this as this works fine for me.  If you can't provide one than I'll have to close this issue as I'm not going to guess at the problem.

ok, let's make this straight to the point, How can I initialize Shiny on Android using version 2.0.0.2279?

> * 1.2 is stable.  Use it if you want to file bugs in the future.  2.0 is still being worked on and is open for PR's, not general usage.

This doesn't seems an option for me since I am using Shiny.Beacons and Shiny.Beacons is not available in 1.2.

**Comment by aritchie** [comment] 2021-01-25 17:52
This is not a support channel and if you aren't going to provide a sample, this is the end of the conversation because 2.0 is not released.

**Closed by aritchie** 2021-01-25 17:52 UTC
Labels: more-info-needed, s/unverified, t/bug 👾

**Comment by arivera12** [comment] 2021-01-25 18:36
@aritchie I upgraded to android 10 and installed the sdk. Now visual studio recognize the missing methods!

![image](https://user-images.githubusercontent.com/5600102/105750130-b4151100-5f1a-11eb-8e8d-c3f2bcda7888.png)

Thanks so much for your support on this.
