### ISSUE TITLE
Crash on `Java.Util.ConcurrentModificationException`

### ISSUE THREAD

**Issue by eli191** [shinyorg/shiny#362] opened 2020-06-24 17:39 UTC
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!  PLEASE DON'T ASK FOR WORKAROUNDS OR TIMELINES - THIS IS FREE SOURCE CODE

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [x] Android
 - [ ] UWP

 PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS

## Feature Library
BluetoothLE

### beta components are not fully done - issues MUST include full reproducible sample and stacktrace or they will be closed without explanation!!!

 - [ ] Core
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Push
 - [ ] Push - Azure Notification Hub
 - [ ] Push - Firebase (beta)
 - [ ] Sensors
 - [ ] AppCenter Logging Integration
 - [ ] Location Sync (beta)
 - [ ] Photo Sync (alpha)
 - [x] BluetoothLE (beta)
 - [ ] Beacons (beta)
 - [ ] SQLite Integration

## Version of Library
1.2.0.1769-beta

## Version of OS(s) listed above with issue
Android 8

## Steps to Reproduce
1. 
2.
3.

## Expected Behavior
No crash

## Actual Behavior
Crash
```
Peripheral+<>c__DisplayClass13_0.<DiscoverServices>b__1 (Shiny.BluetoothLE.Internals.GattEventArgs cb)
Java.Util.ConcurrentModificationException: Exception of type 'Java.Util.ConcurrentModificationException' was thrown.
```
It seems it is from a scan while a connect was attempted (not 100% sure)
```
JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args)
JniPeerMembers+JniInstanceMethods.InvokeAbstractObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters)
BluetoothGatt.get_Services ()
Peripheral+<>c__DisplayClass13_0.<DiscoverServices>b__1 (Shiny.BluetoothLE.Internals.GattEventArgs cb)
AnonymousObserver`1[T].OnNextCore (T value)
ObserverBase`1[T].OnNext (T value)
Subject`1[T].OnNext (T value)
GattCallbacks.OnServicesDiscovered (Android.Bluetooth.BluetoothGatt gatt, Android.Bluetooth.GattStatus status)
BluetoothGattCallback.n_OnServicesDiscovered_Landroid_bluetooth_BluetoothGatt_I (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_gatt, System.Int32 native_status)
(wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.39(intptr,intptr,intptr,int)
java.util.ConcurrentModificationException
java.util.ArrayList$Itr.next ArrayList.java:860
android.bluetooth.BluetoothGatt.getServices BluetoothGatt.java:1118
md5c9cd8eb479667cc7f8e82524ad7834c1.GattCallbacks.n_onServicesDiscovered(Native Method)
md5c9cd8eb479667cc7f8e82524ad7834c1.GattCallbacks.onServicesDiscovered(Unknown Source:0)
android.bluetooth.BluetoothGatt$1$5.run BluetoothGatt.java:330
android.bluetooth.BluetoothGatt.runOrQueueCallback BluetoothGatt.java:789
android.bluetooth.BluetoothGatt.-wrap0(Unknown Source:0)
android.bluetooth.BluetoothGatt$1.onSearchComplete BluetoothGatt.java:326
android.bluetooth.IBluetoothGattCallback$Stub.onTransact IBluetoothGattCallback.java:110
android.os.Binder.execTransact Binder.java:682
```

Thing is the exceptions are handled in the `.Subscribe` so it should not crash the app no?
Thanks!

**Comment by eli191** [comment] 2020-06-25 10:01
Today, I got the same error in debug, it seems that the `DiscoverServices` is looping over and over again even after having obtained the results `onSearchComplete()`

**Comment by aritchie** [comment] 2020-06-25 11:36
@eli191 Please read the requirements of filing issues for beta components.  You need to provide a FULL reproducible sample.

**Comment by josejavieralvarez** [comment] 2020-07-06 11:51
I'm getting a crash on Android 10 devices while running on debug. It is 100% reproducible. See trace below:
`2020-07-06 09:57:41.848 20264-20264/com.xxxx.XXXXX E/mono: Unhandled Exception:
    System.NotSupportedException: Unable to activate instance of type Android.Util.SparseArray`1[E] from native handle 0x85 (key_handle 0xb2b5e96). ---> System.MissingMethodException: No constructor found for Android.Util.SparseArray`1::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership) ---> Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.
       --- End of inner exception stack trace ---
      at Java.Interop.TypeManager.CreateProxy (System.Type type, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x000b5] in <55654ebe9f2a48e6bade2862bb243f94>:0
      at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x00111] in <55654ebe9f2a48e6bade2862bb243f94>:0
       --- End of inner exception stack trace ---
      at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x0017e] in <55654ebe9f2a48e6bade2862bb243f94>:0
      at Java.Lang.Object.GetObject (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type type) [0x00023] in <55654ebe9f2a48e6bade2862bb243f94>:0
      at Java.Lang.Object._GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00017] in <55654ebe9f2a48e6bade2862bb243f94>:0
      at Java.Lang.Object.GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00000] in <55654ebe9f2a48e6bade2862bb243f94>:0
      at Android.Bluetooth.LE.ScanRecord.get_ManufacturerSpecificData () [0x0001f] in <55654ebe9f2a48e6bade2862bb243f94>:0
      at Shiny.BluetoothLE.AdvertisementData+<>c__DisplayClass1_0.<.ctor>b__0 () [0x00000] in d:\a\1\s\src\Shiny.BluetoothLE\Platforms\Android\AdvertisementData.cs:18
      at System.Lazy`1[T].ViaFactory (System.Threading.LazyThreadSafetyMode mode) [0x00043] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/Lazy.cs:333
      at System.Lazy`1[T].ExecutionAndPublication (System.LazyHelper executionAndPublication, System.Boolean useDefaultConstructor) [0x00022] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/Lazy.cs:351
      at System.Lazy`1[T].CreateValue () [0x00074] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/Lazy.cs:431
      at System.Lazy`1[T].get_Value () [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/Lazy.cs:509
      at Shiny.BluetoothLE.AdvertisementData.get_ManufacturerData () [0x00000] in d:\a\1\s\src\Shiny.BluetoothLE\Platforms\Android\AdvertisementData.cs:58
      at Shiny.Beacons.BleManagerExtensions.IsBeacon (Shiny.BluetoothLE.ScanResult result) [0x00000] in d:\a\1\s\src\Shiny.Beacons\Platforms\android+uwp\BleManagerExtensions.cs:24
      at Shiny.Beacons.BleManagerExtensions+<>c.<ScanForBeacons>b__0_0 (Shiny.BluetoothLE.ScanResult x) [0x00000] in d:\a\1\s\src\Shiny.Beacons\Platforms\android+uwp\BleManagerExtensions.cs:18
      at System.Reactive.Linq.ObservableImpl.Where`1+Predicate+_[TSource].OnNext (TSource value) [0x00002] in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Where.cs:44
    --- End of stack trace from previous location where exception was thrown ---
        at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.111(intptr,intptr,int,intptr)
        at (wrapper native-to-managed) Android.Runtime.DynamicMethodNameCounter.111(intptr,intptr,int,intptr)
2020-07-06 09:57:41.851 20264-20264/com.xxx.XXX E/mono-rt: [ERROR] FATAL UNHANDLED EXCEPTION: System.NotSupportedException: Unable to activate instance of type Android.Util.SparseArray`1[E] from native handle 0x85 (key_handle 0xb2b5e96). ---> System.MissingMethodException: No constructor found for Android.Util.SparseArray`1::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership) ---> Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.
       --- End of inner exception stack trace ---
      at Java.Interop.TypeManager.CreateProxy (System.Type type, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x000b5] in <55654ebe9f2a48e6bade2862bb243f94>:0
      at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x00111] in <55654ebe9f2a48e6bade2862bb243f94>:0
       --- End of inner exception stack trace ---
      at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x0017e] in <55654ebe9f2a48e6bade2862bb243f94>:0
      at Java.Lang.Object.GetObject (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type type) [0x00023] in <55654ebe9f2a48e6bade2862bb243f94>:0
      at Java.Lang.Object._GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00017] in <55654ebe9f2a48e6bade2862bb243f94>:0
      at Java.Lang.Object.GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00000] in <55654ebe9f2a48e6bade2862bb243f94>:0
      at Android.Bluetooth.LE.ScanRecord.get_ManufacturerSpecificData () [0x0001f] in <55654ebe9f2a48e6bade2862bb243f94>:0
      at Shiny.BluetoothLE.AdvertisementData+<>c__DisplayClass1_0.<.ctor>b__0 () [0x00000] in d:\a\1\s\src\Shiny.BluetoothLE\Platforms\Android\AdvertisementData.cs:18
      at System.Lazy`1[T].ViaFactory (System.Threading.LazyThreadSafetyMode mode) [0x00043] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/Lazy.cs:333
      at System.Lazy`1[T].ExecutionAndPublication (System.LazyHelper executionAndPublication, System.Boolean useDefaultConstructor) [0x00022] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/Lazy.cs:351
      at System.Lazy`1[T].CreateValue () [0x00074] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/Lazy.cs:431
      at System.Lazy`1[T].get_Value () [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/Lazy.cs:509
      at Shiny.BluetoothLE.AdvertisementData.get_ManufacturerData () [0x00000] in d:\a\1\s\src\Shiny.BluetoothLE\Platforms\Android\AdvertisementData.cs:58
      at Shiny.Beacons.BleManagerExtensions.IsBeacon (Shiny.BluetoothLE.ScanResult result) [0x00000] in d:\a\1\s\src\Shiny.Beacons\Platforms\android+uwp\BleManagerExtensions.cs:24
      at Shiny.Beacons.BleManagerExtensions+<>c.<ScanForBeacons>b__0_0 (Shiny.BluetoothLE.ScanResult x) [0x00000] in d:\a\1\s\src\Shiny.Beacons\Platforms\android+uwp\BleManagerExtensions.cs:18
      at System.Reactive.Linq.ObservableImpl.Where`1+Predicate+_[TSource].OnNext (TSource value) [0x00002] in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Where.cs:44
    --- End of stack trace from previous location where exception was thrown ---
        at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.111(intptr,intptr,int,intptr)
        at (wrapper native-to-managed) Android.Runtime.DynamicMethodNameCounter.111(intptr,intptr,int,intptr)
2020-07-06 09:57:41.919 20264-20264/com.xxx.XXXX E/libc++abi: terminating
    --------- beginning of crash
2020-07-06 09:57:41.920 20264-20264/com.xxxx.XXXX A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 20264 (e.App), pid 20264 (e.App)`

**Comment by aritchie** [comment] 2020-07-06 12:48
@josejavieralvarez The issue isn't even remotely the same.  You also haven't followed what is requested in the issue template.

@eli191 I am closing this issue because once again, you haven't followed up and provided the information that was requested.

**Closed by aritchie** 2020-07-06 12:48 UTC
Labels: more-info-needed, s/unverified, t/bug 👾
