### ISSUE TITLE
UWP Bluetooth (Remote Devices) do not get Disconnected

### ISSUE THREAD

**Issue by dgerchcovich** [shinyorg/shiny#630] opened 2021-07-09 03:18 UTC
# PLEASE READ
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)
 - [ ] iOS
 - [ ] Android
 - [*] **UWP**

PLATFORMS THAT YOU CANNOT FILE ISSUES ON RIGHT NOW: Tizen, watchOS, tvOS, macOS
IF YOU HAVE AN ISSUE WITH DOCUMENTATION, DO NOT FILE AN ISSUE - PR'S ONLY!

## Feature Library
 - [ ] BluetoothLE Client

## Version of Library
2.1.0.2769

## Steps to Reproduce
1. Get the IPeripheral
2. Invoke **CancelConnection()**
3. Peripheral State is set to Disconnected, however the local device is still paired to the remote bluetooth device

## Expected Behavior
1. Both Devices are to be disconnected from each other, and the on Windows (No Connected Devices is supposed to show)

## Actual Behavior
![Storage_71](https://user-images.githubusercontent.com/79491156/125018236-0b1d3580-e0b8-11eb-87db-236368b7f254.PNG)

**Comment by dgerchcovich** [comment] 2021-07-09 03:22
Actually I found the problem. Thanks

**Comment by dgerchcovich** [comment] 2021-07-09 03:50
Even if I manually scan for known peripherals, and scan for the uuid, then cancel the connection, the connection still does not close, and both local and remote machines are still paired

**Comment by dgerchcovich** [comment] 2021-07-09 03:50
thanks

**Comment by wagenheimer** [comment] 2021-07-09 10:27
I have similar issues on an iPhone user, but it's intermittent. Even after disconnecting, the connection still remains open somehow and the user has to turn on/off Bluetooth to be able to connect again to the same device.

**Comment by aritchie** [comment] 2021-07-09 12:22
@dgerchcovich Please include a small reproducible sample.  UWP has long been a pain due to its "reference tracking" disconnection model.

@wagenheimer Your issue is not related to the UWP one.  I have never had a sticky connection on iOS or Android.  They both have proper disconnection models.

**Comment by aritchie** [comment] 2021-07-14 16:38
Needed a reproducible sample of some sort which was not supplied by user.  Closing as per missing info

**Closed by aritchie** 2021-07-14 16:38 UTC
Labels: more-info-needed, s/unverified, t/bug 👾
